// FAQ datasets bilingues pour 6 pages : home + 5 services.
// Optim SEO + AEO (Perplexity, ChatGPT search, Google AI Overviews).
// Home expose 8 Q&A, pages services exposent 10 Q&A. Schema.org FAQPage
// genere automatiquement par <FaqSection /> a partir des items.

export type FaqItem = { question: string; answer: string };

type LocalizedFaq = { en: FaqItem[]; fr: FaqItem[] };

export const FAQ_HOME: LocalizedFaq = {
  en: [
    { question: 'What is Misana?', answer: 'A private services agency on the French Riviera. Five services from Saint-Tropez to Monaco: chauffeur, luxury car rental, yacht charter, helicopter transfers and access to restaurants, hotels and beach clubs.' },
    { question: 'What areas does Misana cover?', answer: 'Saint-Tropez, Cannes, Antibes, Cap d\'Antibes, Cap-Ferrat, Nice and Monaco. Other locations on the French Riviera and beyond on request.' },
    { question: 'How do I book a service?', answer: 'By phone, WhatsApp, email or online form. Reply within a few hours during business hours. One named contact handles your request from quotation to return.' },
    { question: 'When should I book?', answer: 'Last-minute requests are studied case by case. For peak weeks like the Cannes Film Festival, the Monaco Grand Prix, the Cannes Yachting Festival or the Monaco Yacht Show, earlier bookings increase availability.' },
    { question: 'Does Misana coordinate full stays?', answer: 'Yes. Chauffeur, car rental, yacht, helicopter and access can be combined in a single coordination, with one contact handling every booking and every change.' },
    { question: 'Does Misana operate year-round?', answer: 'Yes. The high season runs April to October, but the team operates twelve months a year for residents and winter visitors, including Christmas and February holidays.' },
    { question: 'What languages does Misana operate in?', answer: 'English and French daily. Italian, Arabic and German on request, including multilingual chauffeurs and crews.' },
    { question: 'How is pricing structured?', answer: 'Quoted per service, with all-inclusive rates covering everything required for the booking. Multi-day and full-stay arrangements quoted as a single proposal. The price is locked at booking, never after.' },
  ],
  fr: [
    { question: 'Qu\'est-ce que Misana ?', answer: 'Une agence de services privés sur la Côte d\'Azur. Cinq services de Saint-Tropez à Monaco : chauffeur, location de voitures de luxe, yacht, hélicoptère et accès aux restaurants, hôtels et beach clubs.' },
    { question: 'Quelle est la couverture territoriale ?', answer: 'Saint-Tropez, Cannes, Antibes, Cap d\'Antibes, Cap-Ferrat, Nice et Monaco. Autres lieux sur la Côte d\'Azur et au-delà sur demande.' },
    { question: 'Comment réserver un service ?', answer: 'Par téléphone, WhatsApp, email ou formulaire en ligne. Réponse en quelques heures en journée. Un seul interlocuteur suit votre demande du devis au retour.' },
    { question: 'Quel est le délai de réservation ?', answer: 'Demandes de dernière minute étudiées au cas par cas. Pour les semaines de pic comme le Festival de Cannes, le Grand Prix de Monaco, le Cannes Yachting Festival ou le Monaco Yacht Show, anticiper augmente les disponibilités.' },
    { question: 'Misana coordonne-t-il un séjour complet ?', answer: 'Oui. Chauffeur, voitures, yacht, hélicoptère et accès peuvent être combinés dans une seule coordination, avec un interlocuteur unique pour chaque réservation et chaque changement.' },
    { question: 'Misana opère-t-il toute l\'année ?', answer: 'Oui. La haute saison va d\'avril à octobre, mais l\'équipe opère douze mois par an pour les résidents et les visiteurs hors saison, vacances de Noël et de février incluses.' },
    { question: 'Dans quelles langues Misana opère-t-il ?', answer: 'Français et anglais au quotidien. Italien, arabe et allemand sur demande, y compris chauffeurs et équipages multilingues.' },
    { question: 'Comment fonctionnent les tarifs ?', answer: 'Devis par service, tarifs tout compris couvrant l\'intégralité de la prestation. Les séjours multi-services et les coordinations complètes sont chiffrés en une seule proposition. Le prix est arrêté à la réservation, jamais après.' },
  ],
};

export const FAQ_CHAUFFEUR: LocalizedFaq = {
  en: [
    { question: 'What does the Misana private chauffeur service include?', answer: 'Our chauffeur service includes a professional driver, a luxury vehicle (sedan, SUV or van depending on group size), fuel, parking, all tolls and taxes. Bottled water and Wi-Fi are standard.' },
    { question: 'How much does a private chauffeur cost on the French Riviera?', answer: 'Hourly rates start at around €120 per hour for a sedan with a three-hour minimum. Half-day hire (4 hours) starts at €450, full-day hire (8 hours) at €850. Airport transfers from Nice are quoted as fixed rates.' },
    { question: 'What types of vehicles are available?', answer: 'Our standard fleet includes the Mercedes E-Class, Mercedes S-Class, Mercedes V-Class (up to 7 passengers) and BMW 7 Series. Specific models or larger vehicles can be sourced on request.' },
    { question: 'Can I book a chauffeur for an airport transfer?', answer: 'Yes. We cover Nice Côte d\'Azur (NCE), Cannes Mandelieu (CEQ), Saint-Tropez La Môle (LTT), Marseille (MRS) and Genoa (GOA). Drivers track flight arrival in real time and adjust pickup accordingly.' },
    { question: 'Are Misana chauffeurs multilingual?', answer: 'All our chauffeurs speak French and English. Italian, Arabic and German speaking drivers are available on request.' },
    { question: 'What is the difference between a chauffeur and a taxi or VTC app?', answer: 'A Misana chauffeur is dedicated to you for the booked period, knows your itinerary in advance, holds reservations, parks and waits as long as needed. There is no metered fare and no surge pricing.' },
    { question: 'Can the chauffeur wait during dinner or appointments?', answer: 'Yes. Wait time is included in hourly and daily bookings. The driver remains available throughout the booking and repositions the vehicle discreetly if needed.' },
    { question: 'Do you provide chauffeurs for multi-day stays?', answer: 'Yes. Multi-day chauffeur arrangements typically use the same driver across the stay, ensuring continuity, knowledge of the guest\'s preferences and faster execution.' },
    { question: 'Are child seats available?', answer: 'Yes. Group 0+, group 1, group 2 and booster seats are available at no extra charge. Please specify the child\'s age and weight at booking.' },
    { question: 'How do I book a private chauffeur with Misana?', answer: 'Send us your dates, pickup point, drop-off and any specific vehicle or driver requirement through the request form, phone or WhatsApp. Confirmation is sent within a few hours with the assigned driver\'s name and contact.' },
  ],
  fr: [
    { question: 'Que comprend le service de chauffeur privé Misana ?', answer: 'Notre service chauffeur comprend un conducteur professionnel, un véhicule de luxe (berline, SUV ou van selon la taille du groupe), le carburant, le stationnement, tous les péages et taxes. Eau minérale et Wi-Fi sont inclus en standard.' },
    { question: 'Combien coûte un chauffeur privé sur la Côte d\'Azur ?', answer: 'Les tarifs horaires démarrent à environ 120 € de l\'heure pour une berline avec un minimum de trois heures. La demi-journée (4 heures) démarre à 450 €, la journée complète (8 heures) à 850 €. Les transferts aéroport depuis Nice sont chiffrés en forfait fixe.' },
    { question: 'Quels types de véhicules sont disponibles ?', answer: 'Notre flotte standard comprend Mercedes Classe E, Mercedes Classe S, Mercedes Classe V (jusqu\'à 7 passagers) et BMW Série 7. Des modèles spécifiques ou véhicules plus grands sont disponibles sur demande.' },
    { question: 'Peut-on réserver un chauffeur pour un transfert aéroport ?', answer: 'Oui. Nous couvrons Nice Côte d\'Azur (NCE), Cannes Mandelieu (CEQ), Saint-Tropez La Môle (LTT), Marseille (MRS) et Gênes (GOA). Les chauffeurs suivent l\'arrivée du vol en temps réel et ajustent l\'heure de prise en charge.' },
    { question: 'Les chauffeurs Misana sont-ils multilingues ?', answer: 'Tous nos chauffeurs parlent français et anglais. Des chauffeurs italophones, arabophones et germanophones sont disponibles sur demande.' },
    { question: 'Quelle différence entre un chauffeur et un taxi ou une application VTC ?', answer: 'Un chauffeur Misana est dédié à votre service pour la période réservée, connaît votre itinéraire à l\'avance, garde vos réservations, stationne et attend aussi longtemps que nécessaire. Pas de compteur, pas de tarification dynamique.' },
    { question: 'Le chauffeur peut-il attendre pendant un dîner ou un rendez-vous ?', answer: 'Oui. Le temps d\'attente est inclus dans les forfaits horaires et journaliers. Le conducteur reste disponible pendant toute la durée de la réservation et repositionne le véhicule discrètement si besoin.' },
    { question: 'Proposez-vous des chauffeurs pour des séjours sur plusieurs jours ?', answer: 'Oui. Les missions multi-jours utilisent généralement le même chauffeur tout au long du séjour, ce qui assure la continuité, la connaissance des préférences du client et une exécution plus rapide.' },
    { question: 'Des sièges-auto pour enfants sont-ils disponibles ?', answer: 'Oui. Sièges groupe 0+, groupe 1, groupe 2 et rehausseurs disponibles sans supplément. Merci de préciser l\'âge et le poids de l\'enfant à la réservation.' },
    { question: 'Comment réserver un chauffeur privé avec Misana ?', answer: 'Transmettez-nous vos dates, point de prise en charge, destination et toute exigence spécifique de véhicule ou de chauffeur via le formulaire, par téléphone ou WhatsApp. La confirmation arrive sous quelques heures avec le nom et le contact du chauffeur attribué.' },
  ],
};

export const FAQ_CARS: LocalizedFaq = {
  en: [
    { question: 'What luxury cars can I rent on the French Riviera with Misana?', answer: 'Our fleet covers supercars (Ferrari, Lamborghini, McLaren), grand tourers (Bentley, Aston Martin, Porsche 911), luxury sedans (Mercedes S-Class, Bentley Continental, Rolls-Royce Ghost), luxury SUVs (Range Rover, Bentley Bentayga, Lamborghini Urus) and convertibles.' },
    { question: 'How much does it cost to rent a luxury car on the Côte d\'Azur?', answer: 'Daily rates start at around €600 for a Porsche 911, €900 for a Range Rover, €1,500 for a Ferrari Roma, €2,500 for a Lamborghini Huracán and €3,500+ for a Rolls-Royce. Multi-day rates are degressive.' },
    { question: 'Where can the car be delivered?', answer: 'We deliver across the entire French Riviera: Nice airport, hotel, yacht slip, villa, restaurant or any requested address between Saint-Tropez and Menton. Delivery is included in most multi-day rentals.' },
    { question: 'What is required to rent a supercar?', answer: 'A valid driving licence held for at least 3 years (5 years for some supercars), a passport or ID, a credit card for the deposit and a minimum age of 25 (30 for the high-performance category).' },
    { question: 'Is insurance included in the rental?', answer: 'Yes. Comprehensive insurance is included in every rental. Deposit amounts vary by vehicle category, from €5,000 to €30,000, fully released upon return without incident.' },
    { question: 'Can I rent a car with a chauffeur?', answer: 'Yes. Any vehicle in our fleet can be booked with a chauffeur. This is the recommended option for guests who do not wish to drive in summer traffic or unfamiliar mountain roads.' },
    { question: 'Are there mileage limits?', answer: 'Standard rentals include 200 km per day. Additional kilometres are billed per car category. Unlimited mileage packages are available on request for long itineraries.' },
    { question: 'Can I cross into Italy or Switzerland with a rental car?', answer: 'Yes, with prior notice and an additional cross-border insurance extension. We commonly arrange day trips to Portofino, San Remo and the Italian Lakes.' },
    { question: 'How early should I book a supercar in summer?', answer: 'For July and August we recommend booking at least 6 weeks ahead. Specific models (limited-edition Ferraris, Lamborghini SVJ, Bugatti) require 2 to 3 months notice.' },
    { question: 'Can I rent a car for just a few hours?', answer: 'Standard rental is per 24-hour day. Half-day rentals are available for some categories on request, typically for photoshoots, weddings or short scenic drives.' },
  ],
  fr: [
    { question: 'Quelles voitures de luxe puis-je louer sur la Côte d\'Azur avec Misana ?', answer: 'Notre flotte couvre les supercars (Ferrari, Lamborghini, McLaren), les GT (Bentley, Aston Martin, Porsche 911), les berlines de luxe (Mercedes Classe S, Bentley Continental, Rolls-Royce Ghost), les SUV de luxe (Range Rover, Bentley Bentayga, Lamborghini Urus) et les cabriolets.' },
    { question: 'Combien coûte la location d\'une voiture de luxe sur la Côte d\'Azur ?', answer: 'Les tarifs journaliers démarrent autour de 600 € pour une Porsche 911, 900 € pour un Range Rover, 1 500 € pour une Ferrari Roma, 2 500 € pour une Lamborghini Huracán et 3 500 €+ pour une Rolls-Royce. Les tarifs multi-jours sont dégressifs.' },
    { question: 'Où la voiture peut-elle être livrée ?', answer: 'Nous livrons sur toute la Côte d\'Azur : aéroport de Nice, hôtel, ponton de yacht, villa, restaurant ou toute adresse demandée entre Saint-Tropez et Menton. La livraison est incluse dans la plupart des locations multi-jours.' },
    { question: 'Quelles sont les conditions pour louer une supercar ?', answer: 'Permis de conduire valide depuis au moins 3 ans (5 ans pour certaines supercars), passeport ou pièce d\'identité, carte de crédit pour le dépôt de garantie et âge minimum de 25 ans (30 ans pour la catégorie haute performance).' },
    { question: 'L\'assurance est-elle incluse dans la location ?', answer: 'Oui. L\'assurance tous risques est incluse dans chaque location. Le montant du dépôt de garantie varie selon la catégorie du véhicule, de 5 000 € à 30 000 €, intégralement libéré au retour sans incident.' },
    { question: 'Puis-je louer une voiture avec chauffeur ?', answer: 'Oui. Tous les véhicules de notre flotte sont disponibles avec chauffeur. C\'est l\'option recommandée pour les clients qui ne souhaitent pas conduire dans le trafic estival ou sur les routes de montagne inconnues.' },
    { question: 'Y a-t-il des limites de kilométrage ?', answer: 'Les locations standard incluent 200 km par jour. Les kilomètres supplémentaires sont facturés selon la catégorie. Des forfaits kilométrage illimité sont disponibles sur demande pour les longs itinéraires.' },
    { question: 'Peut-on passer en Italie ou en Suisse avec une voiture de location ?', answer: 'Oui, avec préavis et extension d\'assurance frontalière. Nous arrangeons fréquemment des journées à Portofino, San Remo et sur les lacs italiens.' },
    { question: 'Combien de temps à l\'avance faut-il réserver une supercar en été ?', answer: 'Pour juillet et août, nous recommandons de réserver au moins 6 semaines à l\'avance. Certains modèles spécifiques (Ferrari série limitée, Lamborghini SVJ, Bugatti) demandent 2 à 3 mois de préavis.' },
    { question: 'Peut-on louer une voiture pour seulement quelques heures ?', answer: 'La location standard est de 24 heures. Des locations demi-journée sont disponibles pour certaines catégories sur demande, généralement pour shootings, mariages ou courtes balades panoramiques.' },
  ],
};

export const FAQ_YACHT: LocalizedFaq = {
  en: [
    { question: 'What yachts can I charter with Misana on the French Riviera?', answer: 'Our charter selection ranges from 15-metre day yachts to 50-metre+ superyachts, including motor yachts, sailing yachts and catamarans. Crew is included on every charter.' },
    { question: 'How much does a yacht charter cost on the Côte d\'Azur?', answer: 'Day charters on a 15 to 20-metre motor yacht start at around €4,500 including crew, fuel surcharge excluded. Weekly charters on a 30-metre yacht typically range €60,000 to €120,000. Superyachts above 40 metres are quoted on request.' },
    { question: 'What is included in the charter price?', answer: 'Day charters generally include the yacht, full crew, water toys (paddleboards, snorkelling gear). Fuel, food and beverages are typically billed separately as APA (Advance Provisioning Allowance) for weekly charters.' },
    { question: 'Where do yacht charters depart from?', answer: 'Most departures are from Saint-Tropez, Cannes, Antibes, Nice or Monaco. We can also arrange embarkation at any port between Saint-Tropez and Menton, and one-way charters to Italy, Corsica or the Balearics.' },
    { question: 'How many guests can a yacht accommodate?', answer: 'Day charters typically host 8 to 12 guests. Overnight charters accommodate 6 to 12 guests in cabins, with crew quarters separate. Larger superyachts can host up to 18 guests overnight.' },
    { question: 'What is APA in a yacht charter?', answer: 'APA stands for Advance Provisioning Allowance, generally 25 to 35% of the charter fee, paid before departure. It covers fuel, food, drinks, port fees and any expense incurred during the charter. Unspent funds are refunded.' },
    { question: 'Do I need a licence to charter a yacht?', answer: 'No. Every charter includes a professional crew. Bareboat charters (without crew) require a valid skipper\'s licence and are arranged on request for sailing yachts under 24 metres.' },
    { question: 'What activities are available during a charter?', answer: 'Snorkelling, paddleboarding, jet skis (some yachts), seabobs, inflatable slides, fishing equipment, swim platforms. We can also arrange beach club access, restaurant tenders to shore and helicopter transfers to and from the yacht.' },
    { question: 'When should I book a yacht for July or August?', answer: 'For peak July and August, especially around Bastille Day and the August 15 weekend, we recommend booking 4 to 6 months ahead. Major event weeks (Cannes Lions, Cannes Yachting Festival, Monaco Yacht Show, Monaco Grand Prix) book 6 months in advance.' },
    { question: 'Can the yacht come to a specific port to pick us up?', answer: 'Yes. Subject to charter agreement and port availability, the yacht can reposition to your preferred embarkation point. Repositioning fuel costs may apply for distant pickups.' },
  ],
  fr: [
    { question: 'Quels yachts puis-je affréter avec Misana sur la Côte d\'Azur ?', answer: 'Notre sélection couvre des yachts de jour de 15 mètres jusqu\'aux superyachts de 50 mètres et plus, incluant yachts à moteur, voiliers et catamarans. L\'équipage est inclus sur chaque charter.' },
    { question: 'Combien coûte un charter de yacht sur la Côte d\'Azur ?', answer: 'Les charters journée sur un yacht à moteur de 15 à 20 mètres démarrent autour de 4 500 € équipage inclus, hors surcharge carburant. Les charters à la semaine sur un 30 mètres vont généralement de 60 000 € à 120 000 €. Les superyachts au-delà de 40 mètres sont chiffrés sur demande.' },
    { question: 'Qu\'est-ce qui est inclus dans le prix d\'un charter ?', answer: 'Les charters journée incluent généralement le yacht, l\'équipage complet et les jouets nautiques (paddles, équipement de snorkeling). Le carburant, la nourriture et les boissons sont généralement facturés séparément en APA (Advance Provisioning Allowance) pour les charters à la semaine.' },
    { question: 'D\'où partent les charters de yacht ?', answer: 'La plupart des départs se font depuis Saint-Tropez, Cannes, Antibes, Nice ou Monaco. Nous pouvons aussi arranger l\'embarquement dans tout port entre Saint-Tropez et Menton, ainsi que des charters one-way vers l\'Italie, la Corse ou les Baléares.' },
    { question: 'Combien de passagers un yacht peut-il accueillir ?', answer: 'Les charters journée accueillent généralement 8 à 12 invités. Les charters avec nuitées hébergent 6 à 12 invités en cabines, l\'équipage étant logé séparément. Les superyachts plus grands peuvent accueillir jusqu\'à 18 invités la nuit.' },
    { question: 'Qu\'est-ce que l\'APA dans un charter de yacht ?', answer: 'APA signifie Advance Provisioning Allowance, généralement 25 à 35 % du prix du charter, payée avant le départ. Elle couvre le carburant, la nourriture, les boissons, les taxes portuaires et toute dépense engagée durant le charter. Les fonds non dépensés sont remboursés.' },
    { question: 'Faut-il un permis pour affréter un yacht ?', answer: 'Non. Chaque charter inclut un équipage professionnel. Les charters sans équipage (bareboat) demandent un permis de skipper valide et sont arrangés sur demande pour les voiliers de moins de 24 mètres.' },
    { question: 'Quelles activités sont disponibles pendant un charter ?', answer: 'Snorkeling, paddle, jet skis (selon yacht), seabobs, toboggans gonflables, équipement de pêche, plateformes de bain. Nous pouvons aussi arranger l\'accès aux beach clubs, les tenders vers les restaurants et les transferts hélicoptère vers et depuis le yacht.' },
    { question: 'Quand faut-il réserver un yacht pour juillet ou août ?', answer: 'Pour les pics de juillet et août, notamment autour du 14 juillet et du week-end du 15 août, nous recommandons de réserver 4 à 6 mois à l\'avance. Les grandes semaines événementielles (Cannes Lions, Cannes Yachting Festival, Monaco Yacht Show, Grand Prix de Monaco) se réservent 6 mois à l\'avance.' },
    { question: 'Le yacht peut-il venir nous chercher dans un port spécifique ?', answer: 'Oui. Sous réserve du contrat de charter et de la disponibilité du port, le yacht peut se repositionner à votre point d\'embarquement préféré. Des frais de carburant de repositionnement peuvent s\'appliquer pour les prises en charge éloignées.' },
  ],
};

export const FAQ_HELICOPTER: LocalizedFaq = {
  en: [
    { question: 'What helicopter transfers does Misana operate?', answer: 'We arrange helicopter transfers between all major points on the French Riviera and inland: Nice, Monaco, Cannes, Saint-Tropez, Cap Ferrat, Mougins helipad, plus extensions to Saint-Moritz, Courchevel, Italian Riviera and Corsica.' },
    { question: 'How long does a Nice to Monaco helicopter transfer take?', answer: 'The Nice Côte d\'Azur airport to Monaco Heliport flight takes approximately 7 minutes in the air, around 20 minutes total including boarding and disembarkation. It is the fastest way between the two points.' },
    { question: 'How much does a helicopter transfer cost on the Côte d\'Azur?', answer: 'Nice-Monaco transfers start at around €180 per person on shared service, or €1,400 to €1,800 for a private 4-seat helicopter. Nice-Saint-Tropez private transfers start around €3,500. Rates vary by aircraft type and season.' },
    { question: 'How many passengers can the helicopter carry?', answer: 'Standard light twin helicopters carry 4 to 6 passengers. Larger helicopters (AW139, H145) can carry 7 to 8 passengers. Luggage is typically limited to soft cabin bags; large suitcases may go separately by car.' },
    { question: 'Where do helicopters take off and land?', answer: 'Main helipads include Nice Côte d\'Azur Airport, Monaco Heliport (Le Cap d\'Ail), Cannes Mandelieu, Saint-Tropez La Môle and various private helipads at hotels, villas and yachts on request.' },
    { question: 'Can the helicopter land on a yacht?', answer: 'Yes, if the yacht has a certified helideck or touch-and-go pad. We verify clearance, weather and flight permissions before each transfer. Many superyachts above 40 metres are equipped.' },
    { question: 'What is the luggage allowance for a helicopter transfer?', answer: 'Each passenger is generally allowed one cabin-size soft bag (around 10 kg) plus a personal item. Hard suitcases and excess luggage are typically transferred separately by Misana chauffeur to the destination.' },
    { question: 'Are helicopter transfers cancelled in bad weather?', answer: 'Pilot safety rules apply. In low visibility, strong winds or storms, flights may be delayed or cancelled. In that case, we redirect guests to a chauffeur transfer at no extra charge.' },
    { question: 'Do you offer helicopter scenic flights?', answer: 'Yes. Scenic flights over the Côte d\'Azur, Saint-Tropez, the Estérel, Monaco and the Italian Riviera coastline are available, typically 20 to 60 minutes, departing from Cannes Mandelieu or Monaco.' },
    { question: 'How far in advance should I book a helicopter transfer?', answer: 'Standard transfers can be confirmed 24 to 48 hours ahead off-peak. For Grand Prix week, Festival de Cannes and Monaco Yacht Show, we recommend booking 4 to 6 weeks in advance.' },
  ],
  fr: [
    { question: 'Quels transferts en hélicoptère opère Misana ?', answer: 'Nous organisons des transferts hélicoptère entre tous les points majeurs de la Côte d\'Azur et l\'intérieur : Nice, Monaco, Cannes, Saint-Tropez, Cap Ferrat, hélistation de Mougins, ainsi que des extensions vers Saint-Moritz, Courchevel, la Riviera italienne et la Corse.' },
    { question: 'Combien de temps dure un transfert hélicoptère Nice-Monaco ?', answer: 'Le vol entre l\'aéroport de Nice Côte d\'Azur et l\'héliport de Monaco prend environ 7 minutes en l\'air, soit environ 20 minutes au total embarquement et débarquement compris. C\'est le moyen le plus rapide entre les deux points.' },
    { question: 'Combien coûte un transfert hélicoptère sur la Côte d\'Azur ?', answer: 'Les transferts Nice-Monaco démarrent à environ 180 € par personne en service partagé, ou 1 400 à 1 800 € pour un hélicoptère privé 4 places. Les transferts privés Nice-Saint-Tropez démarrent autour de 3 500 €. Les tarifs varient selon l\'appareil et la saison.' },
    { question: 'Combien de passagers l\'hélicoptère peut-il transporter ?', answer: 'Les hélicoptères bimoteurs standard transportent 4 à 6 passagers. Les appareils plus grands (AW139, H145) peuvent transporter 7 à 8 passagers. Les bagages sont généralement limités aux sacs cabine souples ; les grandes valises peuvent partir séparément par voiture.' },
    { question: 'Où décollent et atterrissent les hélicoptères ?', answer: 'Les principales hélistations sont Nice Côte d\'Azur, l\'héliport de Monaco (Le Cap d\'Ail), Cannes Mandelieu, Saint-Tropez La Môle et diverses hélistations privées dans les hôtels, villas et yachts sur demande.' },
    { question: 'L\'hélicoptère peut-il atterrir sur un yacht ?', answer: 'Oui, si le yacht dispose d\'un hélipont certifié ou d\'une plateforme touch-and-go. Nous vérifions les autorisations, la météo et les permissions de vol avant chaque transfert. La plupart des superyachts au-delà de 40 mètres sont équipés.' },
    { question: 'Quelle est la franchise bagages pour un transfert hélicoptère ?', answer: 'Chaque passager est généralement autorisé un sac cabine souple (environ 10 kg) plus un effet personnel. Les valises rigides et bagages en surplus sont généralement transférés séparément par chauffeur Misana vers la destination.' },
    { question: 'Les transferts hélicoptère sont-ils annulés en cas de mauvais temps ?', answer: 'Les règles de sécurité du pilote s\'appliquent. En cas de visibilité réduite, vents forts ou orages, les vols peuvent être retardés ou annulés. Dans ce cas, nous redirigeons les invités vers un transfert chauffeur sans surcoût.' },
    { question: 'Proposez-vous des vols panoramiques en hélicoptère ?', answer: 'Oui. Des vols panoramiques au-dessus de la Côte d\'Azur, Saint-Tropez, l\'Estérel, Monaco et la côte de la Riviera italienne sont disponibles, généralement 20 à 60 minutes, au départ de Cannes Mandelieu ou Monaco.' },
    { question: 'Combien de temps à l\'avance faut-il réserver un transfert hélicoptère ?', answer: 'Les transferts standard peuvent être confirmés sous 24 à 48 heures hors saison. Pour la semaine du Grand Prix, le Festival de Cannes et le Monaco Yacht Show, nous recommandons de réserver 4 à 6 semaines à l\'avance.' },
  ],
};

export const FAQ_ACCESS: LocalizedFaq = {
  en: [
    { question: 'What does the Misana access service include?', answer: 'Our access service covers restaurant reservations, beach club tables and cabanas, hotel suites, nightclub tables, private events, and introductions to closed addresses across Saint-Tropez, Cannes, Monaco and the Côte d\'Azur.' },
    { question: 'Can Misana book restaurants that are fully booked?', answer: 'Often yes. Through long-standing relationships with maître d\'s and operators across the Riviera, we can secure tables in restaurants showing no availability online, including peak summer Sundays and event weeks.' },
    { question: 'Which beach clubs does Misana cover?', answer: 'We cover all major beach clubs from Pampelonne (Le Club 55, La Réserve, Loulou, Bagatelle, Verde, Tropezina) to Cannes (Plage du Festival, Annex Beach), Monaco and Saint-Jean-Cap-Ferrat. Cabanas, front-row tables and lunch reservations are arranged.' },
    { question: 'Can Misana arrange entry to private members\' clubs?', answer: 'We can arrange access to several private clubs and members-only addresses on the Côte d\'Azur as guest of a member or via host arrangements. Direct membership is not something we sell.' },
    { question: 'How much advance notice is needed for restaurant reservations?', answer: 'Standard tables in good restaurants are typically secured 1 to 2 weeks ahead. Top-tier addresses (3-Michelin-star, exclusive Pampelonne beach clubs in August) need 4 to 8 weeks. Last-minute access is possible on a case-by-case basis.' },
    { question: 'Does Misana book hotel rooms and suites?', answer: 'Yes. We hold preferred-partner status with most luxury hotels on the Côte d\'Azur (Cap-Eden-Roc, Hôtel du Cap-Ferrat, Hôtel de Paris, Carlton, Majestic, Le Byblos), often securing room categories or arrival amenities not available through public channels.' },
    { question: 'Can Misana arrange last-minute restaurant tables in summer?', answer: 'Yes, depending on the address and the day. Even at peak season, our team places several last-minute tables every evening through direct contact with restaurant teams. Outcomes are confirmed within hours.' },
    { question: 'Are private events and venues part of the access service?', answer: 'Yes. Yacht parties, villa rentals for events, private dinners with named chefs, art viewings and gallery introductions are all part of the access offer.' },
    { question: 'How much does the access service cost?', answer: 'Pricing is structured per request, with most restaurant and beach reservations included as part of a Misana stay coordination. Standalone access requests for non-clients are quoted on a case-by-case basis.' },
    { question: 'Can Misana book non-Riviera addresses (Paris, Saint-Moritz, Italy)?', answer: 'Yes, on request. Through our partner network we can arrange restaurant and hotel access in Paris, Saint-Moritz, Courchevel, Milan, Portofino, Capri, London and Marrakech.' },
  ],
  fr: [
    { question: 'Que comprend le service Access de Misana ?', answer: 'Notre service Access couvre les réservations restaurants, tables et cabanes en beach clubs, suites hôtelières, tables en nightclub, événements privés, et mises en relation avec des adresses fermées à Saint-Tropez, Cannes, Monaco et sur toute la Côte d\'Azur.' },
    { question: 'Misana peut-elle réserver des restaurants complets ?', answer: 'Souvent oui. Grâce à des relations établies de longue date avec les maîtres d\'hôtel et opérateurs de la Riviera, nous obtenons des tables dans des restaurants affichant complets en ligne, y compris les dimanches de pic estival et les semaines événementielles.' },
    { question: 'Quels beach clubs Misana couvre-t-elle ?', answer: 'Nous couvrons tous les beach clubs majeurs de Pampelonne (Le Club 55, La Réserve, Loulou, Bagatelle, Verde, Tropezina) à Cannes (Plage du Festival, Annex Beach), Monaco et Saint-Jean-Cap-Ferrat. Cabanes, tables de premier rang et réservations déjeuner sont arrangées.' },
    { question: 'Misana peut-elle organiser l\'entrée dans des clubs privés ?', answer: 'Nous pouvons organiser l\'accès à plusieurs clubs privés et adresses réservées aux membres sur la Côte d\'Azur en tant qu\'invité d\'un membre ou via des arrangements d\'introduction. L\'adhésion directe n\'est pas quelque chose que nous vendons.' },
    { question: 'Combien de temps à l\'avance faut-il réserver un restaurant ?', answer: 'Les tables standard dans les bons restaurants se réservent généralement 1 à 2 semaines à l\'avance. Les adresses les plus recherchées (3 étoiles Michelin, beach clubs exclusifs de Pampelonne en août) demandent 4 à 8 semaines. L\'accès dernière minute est possible au cas par cas.' },
    { question: 'Misana réserve-t-elle des chambres et suites d\'hôtel ?', answer: 'Oui. Nous avons un statut partenaire privilégié avec la plupart des hôtels de luxe de la Côte d\'Azur (Cap-Eden-Roc, Hôtel du Cap-Ferrat, Hôtel de Paris, Carlton, Majestic, Byblos), obtenant souvent des catégories de chambres ou des prestations d\'arrivée non disponibles via les canaux publics.' },
    { question: 'Misana peut-elle obtenir des tables de restaurant en dernière minute en été ?', answer: 'Oui, selon l\'adresse et le jour. Même en pic de saison, notre équipe place plusieurs tables de dernière minute chaque soir par contact direct avec les équipes des restaurants. Les confirmations arrivent en quelques heures.' },
    { question: 'Les événements et lieux privés font-ils partie du service Access ?', answer: 'Oui. Soirées yacht, location de villas pour événements, dîners privés avec chef nommé, visites d\'art et introductions en galerie font tous partie de l\'offre Access.' },
    { question: 'Combien coûte le service Access ?', answer: 'La tarification est structurée par demande, la plupart des réservations restaurants et plages étant incluses dans la coordination d\'un séjour Misana. Les demandes Access autonomes pour non-clients sont chiffrées au cas par cas.' },
    { question: 'Misana peut-elle réserver des adresses hors Côte d\'Azur (Paris, Saint-Moritz, Italie) ?', answer: 'Oui, sur demande. Via notre réseau de partenaires, nous arrangeons l\'accès restaurants et hôtels à Paris, Saint-Moritz, Courchevel, Milan, Portofino, Capri, Londres et Marrakech.' },
  ],
};

// Selecteur par locale.
export function pickFaq(faq: LocalizedFaq, locale: string): FaqItem[] {
  return locale === 'fr' ? faq.fr : faq.en;
}
