// Catalogue location voitures Misana V1.
// Données scrapées Excellence Riviera (operateur Riviera de reference).
// 37 voitures couvrant supercars, sport, SUV, sedan, convertible.

export type RentalCarCategory = 'supercar' | 'sport' | 'suv' | 'sedan' | 'convertible';

export type RentalPriceTiers = {
  oneToThreeDays: number;
  fourToSevenDays: number;
  weekPlus: number;
};

export type RentalConditions = {
  minAge: number;
  securityDeposit: number;
  minDays: number;
  includedKmPerDay: number;
  overageRatePerKm: number;
};

export type RentalCar = {
  id: string;
  brand: string;
  model: string;
  fullName: string;
  category: RentalCarCategory;
  pax: number;
  hp: number;
  topSpeedKmh: number;
  transmission: 'auto' | 'manual';
  fuelType: 'gasoline' | 'hybrid' | 'electric' | 'diesel';
  year: number;
  hero: string;
  images: string[];
  prices: RentalPriceTiers;
  conditions: RentalConditions;
  availableCities: string[];
  badge?: 'popular' | 'flagship';
  desc: string;
  descFr: string;
  bodyEn: string;
  bodyFr: string;
};

export const RENTAL_CARS: RentalCar[] = [
  {
    id: 'bentley-bentayga-s',
    brand: 'Bentley',
    model: 'Bentayga S',
    fullName: 'Bentley Bentayga S',
    category: 'suv',
    pax: 5,
    hp: 600,
    topSpeedKmh: 290,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/bentley-bentayga-4-1.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/bentley-bentayga-4-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/bentley-bentayga-1-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/bentley-bentayga-2-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/bentley-bentayga.jpg',
    ],
    prices: { oneToThreeDays: 1450, fourToSevenDays: 1250, weekPlus: 1000 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Bentley Bentayga S, 600 hp, 290 km/h, 2025.',
    descFr: 'Bentley Bentayga S, 600 ch, 290 km/h, 2025.',
    bodyEn: 'Bentley Bentayga rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Bentley Bentayga S a louer sur la Cote d Azur. 5 places, 600 ch, 290 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'ferrari-812-superfast',
    brand: 'Ferrari',
    model: '812 Superfast',
    fullName: 'Ferrari 812 Superfast',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 340,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2021,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Ferrari-812-Superfast-5.jpg',
    ],
    prices: { oneToThreeDays: 3300, fourToSevenDays: 2800, weekPlus: 2300 },
    conditions: { minAge: 30, securityDeposit: 24000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'flagship',
    desc: 'Ferrari 812 Superfast, 800 hp, 340 km/h, 2021.',
    descFr: 'Ferrari 812 Superfast, 800 ch, 340 km/h, 2021.',
    bodyEn: 'Ferrari 812 Superfast rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Ferrari 812 Superfast a louer sur la Cote d Azur. 2 places, 800 ch, 340 km/h vitesse max, modele 2021. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'bentley-continental-gtc',
    brand: 'Bentley',
    model: 'Continental GTC',
    fullName: 'Bentley Continental GTC',
    category: 'convertible',
    pax: 4,
    hp: 600,
    topSpeedKmh: 318,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Bentley-Continental-GTC-4.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Bentley-Continental-GTC-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Bentley-Continental-GTC-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Bentley-Continental-GTC-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Bentley-Continental-GTC-3.jpg',
    ],
    prices: { oneToThreeDays: 1550, fourToSevenDays: 1300, weekPlus: 1100 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Bentley Continental GTC, 600 hp, 318 km/h, 2025.',
    descFr: 'Bentley Continental GTC, 600 ch, 318 km/h, 2025.',
    bodyEn: 'Bentley Continental GTC rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Bentley Continental GTC a louer sur la Cote d Azur. 4 places, 600 ch, 318 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'ferrari-portofino',
    brand: 'Ferrari',
    model: 'Portofino',
    fullName: 'Ferrari Portofino',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 320,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-6.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-6.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/ferrari-portofino-5.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 13000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 5 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Ferrari Portofino, 800 hp, 320 km/h, 2025.',
    descFr: 'Ferrari Portofino, 800 ch, 320 km/h, 2025.',
    bodyEn: 'Ferrari Portofino rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Ferrari Portofino a louer sur la Cote d Azur. 2 places, 800 ch, 320 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'lamborghini-huracan',
    brand: 'Lamborghini',
    model: 'Huracan',
    fullName: 'Lamborghini Huracan',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 325,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2022,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Lamborghini-Huracan-5.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 18, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 7 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Lamborghini Huracan, 800 hp, 325 km/h, 2022.',
    descFr: 'Lamborghini Huracan, 800 ch, 325 km/h, 2022.',
    bodyEn: 'Lamborghini Huracan rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Lamborghini Huracan a louer sur la Cote d Azur. 2 places, 800 ch, 325 km/h vitesse max, modele 2022. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'lamborghini-urus',
    brand: 'Lamborghini',
    model: 'Urus',
    fullName: 'Lamborghini Urus',
    category: 'supercar',
    pax: 5,
    hp: 600,
    topSpeedKmh: 305,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Lamborghini-Urus-5.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'flagship',
    desc: 'Lamborghini Urus, 600 hp, 305 km/h, 2025.',
    descFr: 'Lamborghini Urus, 600 ch, 305 km/h, 2025.',
    bodyEn: 'Lamborghini Urus rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Lamborghini Urus a louer sur la Cote d Azur. 5 places, 600 ch, 305 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'maserati-grancabrio',
    brand: 'Maserati',
    model: 'GranCabrio',
    fullName: 'Maserati GranCabrio',
    category: 'convertible',
    pax: 4,
    hp: 500,
    topSpeedKmh: 285,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2021,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-01.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-02.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-03.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-04.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Grancabrio-05.jpg',
    ],
    prices: { oneToThreeDays: 1100, fourToSevenDays: 950, weekPlus: 750 },
    conditions: { minAge: 18, securityDeposit: 5000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 5 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Maserati GranCabrio, 500 hp, 285 km/h, 2021.',
    descFr: 'Maserati GranCabrio, 500 ch, 285 km/h, 2021.',
    bodyEn: 'Maserati GranCabrio rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Maserati GranCabrio a louer sur la Cote d Azur. 4 places, 500 ch, 285 km/h vitesse max, modele 2021. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-classe-e-cabriolet',
    brand: 'Mercedes',
    model: 'Classe E Cabriolet',
    fullName: 'Mercedes Classe E Cabriolet',
    category: 'sedan',
    pax: 4,
    hp: 300,
    topSpeedKmh: 230,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2022,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-5-1.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-5-1.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-1.webp',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-2.webp',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-3.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-classe-e-cabriolet-4.webp',
    ],
    prices: { oneToThreeDays: 550, fourToSevenDays: 450, weekPlus: 400 },
    conditions: { minAge: 25, securityDeposit: 4000, minDays: 7, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Mercedes Classe E Cabriolet, 300 hp, 230 km/h, 2022.',
    descFr: 'Mercedes Classe E Cabriolet, 300 ch, 230 km/h, 2022.',
    bodyEn: 'Mercedes E-Class Convertible rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Mercedes Classe E Cabriolet a louer sur la Cote d Azur. 4 places, 300 ch, 230 km/h vitesse max, modele 2022. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-cayenne-turbo',
    brand: 'Porsche',
    model: 'Cayenne Turbo',
    fullName: 'Porsche Cayenne Turbo',
    category: 'suv',
    pax: 5,
    hp: 500,
    topSpeedKmh: 286,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-01.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-02.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-03.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-04.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-Cayenne-Turbo-05.jpg',
    ],
    prices: { oneToThreeDays: 950, fourToSevenDays: 800, weekPlus: 650 },
    conditions: { minAge: 30, securityDeposit: 8000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'popular',
    desc: 'Porsche Cayenne Turbo, 500 hp, 286 km/h, 2025.',
    descFr: 'Porsche Cayenne Turbo, 500 ch, 286 km/h, 2025.',
    bodyEn: 'Porsche Cayenne Turbo rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche Cayenne Turbo a louer sur la Cote d Azur. 5 places, 500 ch, 286 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-911-carrera-4s',
    brand: 'Porsche',
    model: '911 Carrera 4S',
    fullName: 'Porsche 911 Carrera 4S',
    category: 'sport',
    pax: 4,
    hp: 600,
    topSpeedKmh: 304,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-01.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-02.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-03.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-04.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-05.jpg',
    ],
    prices: { oneToThreeDays: 900, fourToSevenDays: 750, weekPlus: 650 },
    conditions: { minAge: 21, securityDeposit: 8000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'popular',
    desc: 'Porsche 911 Carrera 4S, 600 hp, 304 km/h, 2025.',
    descFr: 'Porsche 911 Carrera 4S, 600 ch, 304 km/h, 2025.',
    bodyEn: 'Porsche 911 Carrera 4S rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche 911 Carrera 4S a louer sur la Cote d Azur. 4 places, 600 ch, 304 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'rolls-royce-cullinan',
    brand: 'Rolls Royce',
    model: 'Cullinan',
    fullName: 'Rolls Royce Cullinan',
    category: 'suv',
    pax: 5,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-01.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-02.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-03.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-04.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Cullinan-05.jpg',
    ],
    prices: { oneToThreeDays: 2750, fourToSevenDays: 2350, weekPlus: 1900 },
    conditions: { minAge: 25, securityDeposit: 25000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'flagship',
    desc: 'Rolls Royce Cullinan, 400 hp, 250 km/h, 2025.',
    descFr: 'Rolls Royce Cullinan, 400 ch, 250 km/h, 2025.',
    bodyEn: 'Rolls Royce Cullinan rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Rolls Royce Cullinan a louer sur la Cote d Azur. 5 places, 400 ch, 250 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'maserati-levante',
    brand: 'Maserati',
    model: 'Levante',
    fullName: 'Maserati Levante',
    category: 'suv',
    pax: 5,
    hp: 300,
    topSpeedKmh: 230,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-01.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-02.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-03.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-04.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Maserati-Levante-05.jpg',
    ],
    prices: { oneToThreeDays: 1000, fourToSevenDays: 850, weekPlus: 700 },
    conditions: { minAge: 18, securityDeposit: 7000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Maserati Levante, 300 hp, 230 km/h, 2025.',
    descFr: 'Maserati Levante, 300 ch, 230 km/h, 2025.',
    bodyEn: 'Maserati Levante rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Maserati Levante a louer sur la Cote d Azur. 5 places, 300 ch, 230 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'rolls-royce-dawn',
    brand: 'Rolls Royce',
    model: 'Dawn',
    fullName: 'Rolls Royce Dawn',
    category: 'convertible',
    pax: 4,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2021,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-1.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-2.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-3.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Rolls-Royce-Dawn-5.jpg',
    ],
    prices: { oneToThreeDays: 3000, fourToSevenDays: 2550, weekPlus: 2100 },
    conditions: { minAge: 21, securityDeposit: 25000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Rolls Royce Dawn, 400 hp, 250 km/h, 2021.',
    descFr: 'Rolls Royce Dawn, 400 ch, 250 km/h, 2021.',
    bodyEn: 'Rolls Royce Dawn rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Rolls Royce Dawn a louer sur la Cote d Azur. 4 places, 400 ch, 250 km/h vitesse max, modele 2021. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'range-rover-sport-svr',
    brand: 'Range Rover',
    model: 'Sport SVR',
    fullName: 'Range Rover Sport SVR',
    category: 'suv',
    pax: 5,
    hp: 500,
    topSpeedKmh: 280,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-Featured.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-01-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-02-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-03-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-04-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-05-1.jpg',
    ],
    prices: { oneToThreeDays: 900, fourToSevenDays: 750, weekPlus: 650 },
    conditions: { minAge: 18, securityDeposit: 7000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Range Rover Sport SVR, 500 hp, 280 km/h, 2025.',
    descFr: 'Range Rover Sport SVR, 500 ch, 280 km/h, 2025.',
    bodyEn: 'Range Rover Sport SVR rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Range Rover Sport SVR a louer sur la Cote d Azur. 5 places, 500 ch, 280 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-sl-63-amg-roadster',
    brand: 'Mercedes',
    model: 'SL 63 AMG Roadster',
    fullName: 'Mercedes SL 63 AMG Roadster',
    category: 'convertible',
    pax: 4,
    hp: 600,
    topSpeedKmh: 315,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-a.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-a.jpg',
    ],
    prices: { oneToThreeDays: 1150, fourToSevenDays: 1000, weekPlus: 800 },
    conditions: { minAge: 30, securityDeposit: 10000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Mercedes SL 63 AMG Roadster, 600 hp, 315 km/h, 2025.',
    descFr: 'Mercedes SL 63 AMG Roadster, 600 ch, 315 km/h, 2025.',
    bodyEn: 'Location Mercedes SL 63 AMG Roadster à St Tropez, Cannes, Monaco. Voitures récentes, soigneusement entretenues et inspectées avant chaque location.',
    bodyFr: 'Mercedes SL 63 AMG Roadster a louer sur la Cote d Azur. 4 places, 600 ch, 315 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'lamborghini-hurac-n-evo-spyder',
    brand: 'Lamborghini',
    model: 'Huracán Evo Spyder',
    fullName: 'Lamborghini Huracán Evo Spyder',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 325,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/04/Lamborghini-Huracan-Evo-Spyder-5.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Lamborghini-Huracan-Evo-Spyder-5.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Lamborghini-Huracan-Evo-Spyder-1-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Lamborghini-Huracan-Evo-Spyder-2-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Lamborghini-Huracan-Evo-Spyder-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/lamborghini-huracan-evo-spyder-5-2.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Lamborghini Huracán Evo Spyder, 800 hp, 325 km/h, 2025.',
    descFr: 'Lamborghini Huracán Evo Spyder, 800 ch, 325 km/h, 2025.',
    bodyEn: 'Lamborghini Huracán Evo Spyder rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Lamborghini Huracán Evo Spyder a louer sur la Cote d Azur. 2 places, 800 ch, 325 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'ferrari-f8-spider',
    brand: 'Ferrari',
    model: 'F8 Spider',
    fullName: 'Ferrari F8 Spider',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 340,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/04/Ferrari-F8-Spider-6-1.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Ferrari-F8-Spider-6-1.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 20000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Ferrari F8 Spider, 800 hp, 340 km/h, 2025.',
    descFr: 'Ferrari F8 Spider, 800 ch, 340 km/h, 2025.',
    bodyEn: 'Ferrari F8 Spider rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Ferrari F8 Spider a louer sur la Cote d Azur. 2 places, 800 ch, 340 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-992-carrera-s-cabriolet',
    brand: 'Porsche',
    model: '992 Carrera S cabriolet',
    fullName: 'Porsche 992 Carrera S cabriolet',
    category: 'convertible',
    pax: 4,
    hp: 600,
    topSpeedKmh: 304,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-992-Carrera-4s-interior.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-992-Carrera-4s-interior.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/05/Porsche-992-Carrera-GTS-8.jpg',
    ],
    prices: { oneToThreeDays: 1250, fourToSevenDays: 1050, weekPlus: 900 },
    conditions: { minAge: 30, securityDeposit: 10000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche 992 Carrera S cabriolet, 600 hp, 304 km/h, 2025.',
    descFr: 'Porsche 992 Carrera S cabriolet, 600 ch, 304 km/h, 2025.',
    bodyEn: 'Porsche 992 Carrera 4S Convertible rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche 992 Carrera S cabriolet a louer sur la Cote d Azur. 4 places, 600 ch, 304 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'range-rover-vogue-l',
    brand: 'Range Rover',
    model: 'Vogue L',
    fullName: 'Range Rover Vogue L',
    category: 'suv',
    pax: 7,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Autobiography.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Autobiography.jpg',
    ],
    prices: { oneToThreeDays: 900, fourToSevenDays: 750, weekPlus: 650 },
    conditions: { minAge: 25, securityDeposit: 7000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    badge: 'popular',
    desc: 'Range Rover Vogue L, 400 hp, 250 km/h, 2025.',
    descFr: 'Range Rover Vogue L, 400 ch, 250 km/h, 2025.',
    bodyEn: 'Range Rover Vogue L rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Range Rover Vogue L a louer sur la Cote d Azur. 7 places, 400 ch, 250 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'aston-martin-db12-volante',
    brand: 'Aston Martin',
    model: 'DB12 Volante',
    fullName: 'Aston Martin DB12 Volante',
    category: 'convertible',
    pax: 4,
    hp: 800,
    topSpeedKmh: 325,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/aston-martin-db12-volante-6.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/aston-martin-db12-volante-6.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/aston-martin-db12-volante-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/aston-martin-db12-volante-4.jpg',
    ],
    prices: { oneToThreeDays: 1700, fourToSevenDays: 1450, weekPlus: 1200 },
    conditions: { minAge: 30, securityDeposit: 20000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    badge: 'flagship',
    desc: 'Aston Martin DB12 Volante, 800 hp, 325 km/h, 2025.',
    descFr: 'Aston Martin DB12 Volante, 800 ch, 325 km/h, 2025.',
    bodyEn: 'Aston Martin DB12 Volante rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Aston Martin DB12 Volante a louer sur la Cote d Azur. 4 places, 800 ch, 325 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-maybach-classe-s',
    brand: 'Mercedes',
    model: 'Maybach Classe S',
    fullName: 'Mercedes Maybach Classe S',
    category: 'sedan',
    pax: 5,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'diesel',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-Classe-S-3.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-Classe-S-3.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-Classe-S-1.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-Classe-S-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/06/Mercedes-Maybach-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-6.png',
    ],
    prices: { oneToThreeDays: 550, fourToSevenDays: 450, weekPlus: 400 },
    conditions: { minAge: 25, securityDeposit: 4000, minDays: 7, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'popular',
    desc: 'Mercedes Maybach Classe S, 400 hp, 250 km/h, 2025.',
    descFr: 'Mercedes Maybach Classe S, 400 ch, 250 km/h, 2025.',
    bodyEn: 'Mercedes Maybach S-Class rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Mercedes Maybach Classe S a louer sur la Cote d Azur. 5 places, 400 ch, 250 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-cayenne-s-coup',
    brand: 'Porsche',
    model: 'Cayenne S Coupé',
    fullName: 'Porsche Cayenne S Coupé',
    category: 'suv',
    pax: 5,
    hp: 400,
    topSpeedKmh: 253,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-cayenne-S-coupe.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-cayenne-S-coupe.png',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-Cayenne-S-Hybrid-6.jpg',
    ],
    prices: { oneToThreeDays: 950, fourToSevenDays: 800, weekPlus: 650 },
    conditions: { minAge: 30, securityDeposit: 8000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche Cayenne S Coupé, 400 hp, 253 km/h, 2025.',
    descFr: 'Porsche Cayenne S Coupé, 400 ch, 253 km/h, 2025.',
    bodyEn: 'Porsche Cayenne S Coupé rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche Cayenne S Coupé a louer sur la Cote d Azur. 5 places, 400 ch, 253 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'ferrari-roma-spider',
    brand: 'Ferrari',
    model: 'Roma Spider',
    fullName: 'Ferrari Roma Spider',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 320,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-6.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-6.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-roma-spider-5.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Ferrari Roma Spider, 800 hp, 320 km/h, 2025.',
    descFr: 'Ferrari Roma Spider, 800 ch, 320 km/h, 2025.',
    bodyEn: 'Ferrari Roma Spider rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Ferrari Roma Spider a louer sur la Cote d Azur. 2 places, 800 ch, 320 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'ferrari-296-gts',
    brand: 'Ferrari',
    model: '296 GTS',
    fullName: 'Ferrari 296 GTS',
    category: 'supercar',
    pax: 2,
    hp: 800,
    topSpeedKmh: 330,
    transmission: 'auto',
    fuelType: 'hybrid',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-296-GTS.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-296-GTS.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-296-GTS.1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-296-GTS.2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Ferrari-296-GTS.3.jpg',
    ],
    prices: { oneToThreeDays: 2900, fourToSevenDays: 2450, weekPlus: 2050 },
    conditions: { minAge: 30, securityDeposit: 20000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 8 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Ferrari 296 GTS, 800 hp, 330 km/h, 2025.',
    descFr: 'Ferrari 296 GTS, 800 ch, 330 km/h, 2025.',
    bodyEn: 'Ferrari 296 GTS rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Ferrari 296 GTS a louer sur la Cote d Azur. 2 places, 800 ch, 330 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-classe-e',
    brand: 'Mercedes',
    model: 'Classe E',
    fullName: 'Mercedes Classe E',
    category: 'sedan',
    pax: 5,
    hp: 300,
    topSpeedKmh: 240,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2023,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-a-1.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-a-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-3-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-4-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-6.png',
    ],
    prices: { oneToThreeDays: 550, fourToSevenDays: 450, weekPlus: 400 },
    conditions: { minAge: 25, securityDeposit: 2000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 1 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Mercedes Classe E, 300 hp, 240 km/h, 2023.',
    descFr: 'Mercedes Classe E, 300 ch, 240 km/h, 2023.',
    bodyEn: 'Mercedes Classe E rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Mercedes Classe E a louer sur la Cote d Azur. 5 places, 300 ch, 240 km/h vitesse max, modele 2023. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-gle-53-amg',
    brand: 'Mercedes',
    model: 'GLE 53 AMG',
    fullName: 'Mercedes GLE 53 AMG',
    category: 'suv',
    pax: 5,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-6.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-6.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-2.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-3.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-4.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-GLE-53-AMG-5.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Mercedes-Classe-E-a-1.jpg',
    ],
    prices: { oneToThreeDays: 1100, fourToSevenDays: 950, weekPlus: 750 },
    conditions: { minAge: 25, securityDeposit: 10000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Mercedes GLE 53 AMG, 400 hp, 250 km/h, 2025.',
    descFr: 'Mercedes GLE 53 AMG, 400 ch, 250 km/h, 2025.',
    bodyEn: 'Mercedes GLE 53 AMG rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Mercedes GLE 53 AMG a louer sur la Cote d Azur. 5 places, 400 ch, 250 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-cayenne-turbo-e',
    brand: 'Porsche',
    model: 'Cayenne Turbo E',
    fullName: 'Porsche Cayenne Turbo E',
    category: 'suv',
    pax: 5,
    hp: 500,
    topSpeedKmh: 286,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-5.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-5.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/porsche-cayenne-turbo-s-e-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-Cayenne-S-Hybrid-6.jpg',
    ],
    prices: { oneToThreeDays: 950, fourToSevenDays: 800, weekPlus: 650 },
    conditions: { minAge: 30, securityDeposit: 8000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche Cayenne Turbo E, 500 hp, 286 km/h, 2025.',
    descFr: 'Porsche Cayenne Turbo E, 500 ch, 286 km/h, 2025.',
    bodyEn: 'Porsche Cayenne Turbo E rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche Cayenne Turbo E a louer sur la Cote d Azur. 5 places, 500 ch, 286 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-macan-gts',
    brand: 'Porsche',
    model: 'Macan GTS',
    fullName: 'Porsche Macan GTS',
    category: 'suv',
    pax: 5,
    hp: 500,
    topSpeedKmh: 272,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2023,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-Macan-GTS-4.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-Macan-GTS-4.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-Macan-GTS-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-Macan-GTS-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-Macan-GTS-3.jpg',
    ],
    prices: { oneToThreeDays: 950, fourToSevenDays: 800, weekPlus: 650 },
    conditions: { minAge: 25, securityDeposit: 9000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 2 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche Macan GTS, 500 hp, 272 km/h, 2023.',
    descFr: 'Porsche Macan GTS, 500 ch, 272 km/h, 2023.',
    bodyEn: 'Porsche Macan GTS rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche Macan GTS a louer sur la Cote d Azur. 5 places, 500 ch, 272 km/h vitesse max, modele 2023. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'range-rover-defender-d130',
    brand: 'Range Rover',
    model: 'Defender D130',
    fullName: 'Range Rover Defender D130',
    category: 'suv',
    pax: 8,
    hp: 300,
    topSpeedKmh: 191,
    transmission: 'auto',
    fuelType: 'diesel',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Land-Rover-Defender-D130-4.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Land-Rover-Defender-D130-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Land-Rover-Defender-D130-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Land-Rover-Defender-D130-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Land-Rover-Defender-D130-3.jpg',
    ],
    prices: { oneToThreeDays: 900, fourToSevenDays: 750, weekPlus: 650 },
    conditions: { minAge: 25, securityDeposit: 7000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Range Rover Defender D130, 300 hp, 191 km/h, 2025.',
    descFr: 'Range Rover Defender D130, 300 ch, 191 km/h, 2025.',
    bodyEn: 'Land Rover Defender D130 rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Range Rover Defender D130 a louer sur la Cote d Azur. 8 places, 300 ch, 191 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-992-carrera-gts-cabriolet',
    brand: 'Porsche',
    model: '992 Carrera GTS cabriolet',
    fullName: 'Porsche 992 Carrera GTS cabriolet',
    category: 'convertible',
    pax: 4,
    hp: 500,
    topSpeedKmh: 280,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/05/Porsche-992-Carrera-GTS-8.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/05/Porsche-992-Carrera-GTS-8.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Porsche-911-Carrera-4S-Cabriolet-Featured.jpg',
    ],
    prices: { oneToThreeDays: 1250, fourToSevenDays: 1050, weekPlus: 900 },
    conditions: { minAge: 30, securityDeposit: 10000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche 992 Carrera GTS cabriolet, 500 hp, 280 km/h, 2025.',
    descFr: 'Porsche 992 Carrera GTS cabriolet, 500 ch, 280 km/h, 2025.',
    bodyEn: 'Porsche 992 Carrera GTS Convertible rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche 992 Carrera GTS cabriolet a louer sur la Cote d Azur. 4 places, 500 ch, 280 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-cayenne-s-hybride',
    brand: 'Porsche',
    model: 'Cayenne S Hybride',
    fullName: 'Porsche Cayenne S Hybride',
    category: 'suv',
    pax: 5,
    hp: 400,
    topSpeedKmh: 265,
    transmission: 'auto',
    fuelType: 'hybrid',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-Cayenne-S-Hybrid-6.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-Cayenne-S-Hybrid-6.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2023/04/Porsche-cayenne-S-coupe.png',
    ],
    prices: { oneToThreeDays: 950, fourToSevenDays: 800, weekPlus: 650 },
    conditions: { minAge: 25, securityDeposit: 7000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche Cayenne S Hybride, 400 hp, 265 km/h, 2025.',
    descFr: 'Porsche Cayenne S Hybride, 400 ch, 265 km/h, 2025.',
    bodyEn: 'Porsche Cayenne S Hybrid rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche Cayenne S Hybride a louer sur la Cote d Azur. 5 places, 400 ch, 265 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'bentley-mulsanne',
    brand: 'Bentley',
    model: 'Mulsanne',
    fullName: 'Bentley Mulsanne',
    category: 'sedan',
    pax: 5,
    hp: 600,
    topSpeedKmh: 296,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2023,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-7.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-7.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Bentley-Mulsanne-5.jpg',
    ],
    prices: { oneToThreeDays: 1050, fourToSevenDays: 900, weekPlus: 750 },
    conditions: { minAge: 30, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 6 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Bentley Mulsanne, 600 hp, 296 km/h, 2023.',
    descFr: 'Bentley Mulsanne, 600 ch, 296 km/h, 2023.',
    bodyEn: 'Bentley Mulsanne rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Bentley Mulsanne a louer sur la Cote d Azur. 5 places, 600 ch, 296 km/h vitesse max, modele 2023. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'aston-martin-vantage-v8',
    brand: 'Aston Martin',
    model: 'Vantage V8',
    fullName: 'Aston Martin Vantage V8',
    category: 'sport',
    pax: 2,
    hp: 500,
    topSpeedKmh: 282,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/aston-martin-vantage-4.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/aston-martin-vantage-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/aston-martin-vantage-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/aston-martin-vantage-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/aston-martin-vantage-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/aston-martin-db12-volante-6.jpg',
    ],
    prices: { oneToThreeDays: 1450, fourToSevenDays: 1250, weekPlus: 1000 },
    conditions: { minAge: 25, securityDeposit: 15000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Aston Martin Vantage V8, 500 hp, 282 km/h, 2025.',
    descFr: 'Aston Martin Vantage V8, 500 ch, 282 km/h, 2025.',
    bodyEn: 'Aston Martin Vantage rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Aston Martin Vantage V8 a louer sur la Cote d Azur. 2 places, 500 ch, 282 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'porsche-992-carrera-turbo-s-911',
    brand: 'Porsche',
    model: '992 Carrera Turbo S (911)',
    fullName: 'Porsche 992 Carrera Turbo S (911)',
    category: 'sport',
    pax: 4,
    hp: 800,
    topSpeedKmh: 330,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-8.jpg.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-8.jpg.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-1.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/Porsche-991-Turbo-S-992-7.jpg',
    ],
    prices: { oneToThreeDays: 1050, fourToSevenDays: 900, weekPlus: 750 },
    conditions: { minAge: 30, securityDeposit: 13000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 5 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Porsche 992 Carrera Turbo S (911), 800 hp, 330 km/h, 2025.',
    descFr: 'Porsche 992 Carrera Turbo S (911), 800 ch, 330 km/h, 2025.',
    bodyEn: 'Porsche 992 Turbo S (911) rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Porsche 992 Carrera Turbo S (911) a louer sur la Cote d Azur. 4 places, 800 ch, 330 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'mercedes-classe-g63-amg',
    brand: 'Mercedes',
    model: 'Classe G63 AMG',
    fullName: 'Mercedes Classe G63 AMG',
    category: 'suv',
    pax: 4,
    hp: 300,
    topSpeedKmh: 220,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-5.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-5.png',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-3.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-4.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Mercedes-G63-AMG-1-1.jpg',
    ],
    prices: { oneToThreeDays: 900, fourToSevenDays: 750, weekPlus: 650 },
    conditions: { minAge: 30, securityDeposit: 8000, minDays: 3, includedKmPerDay: 200, overageRatePerKm: 3 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    badge: 'popular',
    desc: 'Mercedes Classe G63 AMG, 300 hp, 220 km/h, 2025.',
    descFr: 'Mercedes Classe G63 AMG, 300 ch, 220 km/h, 2025.',
    bodyEn: 'Mercedes G63 AMG rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Mercedes Classe G63 AMG a louer sur la Cote d Azur. 4 places, 300 ch, 220 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'range-rover-vogue-l-autobiography',
    brand: 'Range Rover',
    model: 'Vogue L Autobiography',
    fullName: 'Range Rover Vogue L Autobiography',
    category: 'suv',
    pax: 7,
    hp: 300,
    topSpeedKmh: 225,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-Featured.jpg',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2020/05/Range-Rover-Sport-SVR-Featured.jpg',
    ],
    prices: { oneToThreeDays: 1100, fourToSevenDays: 950, weekPlus: 750 },
    conditions: { minAge: 25, securityDeposit: 10000, minDays: 5, includedKmPerDay: 150, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    
    desc: 'Range Rover Vogue L Autobiography, 300 hp, 225 km/h, 2025.',
    descFr: 'Range Rover Vogue L Autobiography, 300 ch, 225 km/h, 2025.',
    bodyEn: 'Range Rover Vogue L Autobiography rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Range Rover Vogue L Autobiography a louer sur la Cote d Azur. 7 places, 300 ch, 225 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  },
  {
    id: 'audi-rs6-performance',
    brand: 'Audi',
    model: 'RS6 Performance',
    fullName: 'Audi RS6 Performance',
    category: 'sedan',
    pax: 5,
    hp: 400,
    topSpeedKmh: 250,
    transmission: 'auto',
    fuelType: 'gasoline',
    year: 2025,
    hero: 'https://excellenceriviera.com/wp-content/uploads/2024/04/audi-rs6-performance-4.png',
    images: [
      'https://excellenceriviera.com/wp-content/uploads/2024/04/audi-rs6-performance-4.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/audi-rs6-performance-1.png',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/audi-rs6-performance-2.jpg',
      'https://excellenceriviera.com/wp-content/uploads/2024/04/audi-rs6-performance-3.jpg',
    ],
    prices: { oneToThreeDays: 600, fourToSevenDays: 500, weekPlus: 400 },
    conditions: { minAge: 30, securityDeposit: 10000, minDays: 3, includedKmPerDay: 150, overageRatePerKm: 4 },
    availableCities: ['nice', 'cannes', 'monaco', 'saint-tropez', 'cap-ferrat', 'cap-d-antibes', 'eze', 'menton'],
    desc: 'Audi RS6 Performance, 400 hp, 250 km/h, 2025.',
    descFr: 'Audi RS6 Performance, 400 ch, 250 km/h, 2025.',
    bodyEn: 'Audi RS6 Performance rental in St Tropez, Cannes, Monaco. Our cars are recent, carefully maintained and inspected before each rental.',
    bodyFr: 'Audi RS6 Performance a louer sur la Cote d Azur. 5 places, 400 ch, 250 km/h vitesse max, modele 2025. Livraison Cannes, Monaco, Saint-Tropez, Nice. Assurance incluse, conciergerie vingt-quatre heures pendant la location.',
  }];

export function findRentalCarById(id: string | undefined) {
  if (!id) return undefined;
  return RENTAL_CARS.find((c) => c.id === id);
}

export function rentalDailyRate(car: RentalCar, days: number): number {
  if (days >= 7) return car.prices.weekPlus;
  if (days >= 4) return car.prices.fourToSevenDays;
  return car.prices.oneToThreeDays;
}

export function rentalTotal(car: RentalCar, days: number): number {
  return rentalDailyRate(car, days) * Math.max(1, days);
}

export const RENTAL_CATEGORIES: { id: RentalCarCategory; label: string; labelFr: string }[] = [
  { id: 'sport', label: 'Performance', labelFr: 'Performance' },
  { id: 'supercar', label: 'Supercar', labelFr: 'Supercar' },
  { id: 'suv', label: 'SUV', labelFr: 'SUV' },
  { id: 'convertible', label: 'Convertible', labelFr: 'Cabriolet' },
  { id: 'sedan', label: 'Sedan', labelFr: 'Berline' },
];

export function rentalBrands(): string[] {
  const set = new Set<string>();
  for (const c of RENTAL_CARS) set.add(c.brand);
  return Array.from(set).sort();
}

export const RENTAL_PRICE_BUCKETS: { id: string; label: string; min: number; max: number }[] = [
  { id: 'under-1000', label: 'Up to €1,000', min: 0, max: 1000 },
  { id: '1000-2000', label: '€1,000 - €2,000', min: 1000, max: 2000 },
  { id: '2000-3000', label: '€2,000 - €3,000', min: 2000, max: 3000 },
  { id: '3000-plus', label: '€3,000 +', min: 3000, max: 999999 },
];
